### PR TITLE
My feature

### PR DESCRIPTION
**Pull request by MarvellousUbani**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Nicely done @MarvellousUbani 👍
Great job on this project. You almost got everything right. But before merging to master, we need to do some changes to make it in line with Microverse guidelines.

- Navbar

- [ ] The input tag from the navbar should have the focus effect enabled.

- Main content links (The 3 main sentences)

- [ ] There should be three links (each one inside an anchor tag).

- [ ] Each link is an `a` HTML tag, with a `div` tag inside it.

- [ ] The `div` tag inside the `a` tag should use an image as background. The text on the original page is actually an image. This approach is required by Microverse guidelines. There is no need to use img tag here. Only `a` tag and `div`.

- Footer

- [ ] Microverse guidelines require the 4 promo images inside the footer. The footer is divided into two parts, top, and bottom. The 4 promo images must be part of the top part of the footer.

- [ ] The top part is made of four `a` tags with `div` tags inside it

- [ ] The `div`s inside the `a` tags should use an image as a background. The same approach of the 3 main sentences.

Kindly make these changes and submit for code review again.

**Comment by bolah2009** [comment]
Currently under review

**Review by bolah2009 — APPROVED** [review]
## Nice Job [Marvellous](../../)  :clap: 

The [clone](https://raw.githack.com/MarvellousUbani/Apple-Website-Clone/my-feature/index.html) looks  good to me. :+1:

##### Consider checking these [errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2FMarvellousUbani%2FApple-Website-Clone%2Fmy-feature%2Findex.html) before merging.

Good luck with your next project.

Cheers
[Bola](https://bolabuari.com/)

**Review by bolah2009 — COMMENTED** [review]
`SUGGESTION`

Consider adding hover effects on the navigation links. See below: 

preffered apple nav hover

**Pull request merged**
